# Get Started

After forking this notebook, run the code in the following cell:

In [1]:
# import package with helper functions 
import bq_helper

# create a helper object for this dataset
accidents = bq_helper.BigQueryHelper(active_project="bigquery-public-data",
                                   dataset_name="nhtsa_traffic_fatalities")

In [2]:
accidents.list_tables()

['accident_2015',
 'accident_2016',
 'cevent_2015',
 'cevent_2016',
 'damage_2015',
 'damage_2016',
 'distract_2015',
 'distract_2016',
 'drimpair_2015',
 'drimpair_2016',
 'factor_2015',
 'factor_2016',
 'maneuver_2015',
 'maneuver_2016',
 'nmcrash_2015',
 'nmcrash_2016',
 'nmimpair_2015',
 'nmimpair_2016',
 'nmprior_2015',
 'nmprior_2016',
 'parkwork_2015',
 'parkwork_2016',
 'pbtype_2015',
 'pbtype_2016',
 'person_2015',
 'person_2016',
 'safetyeq_2015',
 'safetyeq_2016',
 'vehicle_2015',
 'vehicle_2016',
 'vevent_2015',
 'vevent_2016',
 'vindecode_2015',
 'vindecode_2016',
 'violatn_2015',
 'violatn_2016',
 'vision_2015',
 'vision_2016',
 'vsoe_2015',
 'vsoe_2016']

Then write the code to answer the questions below

# Questions

#### 1) Which hours of the day do the most accidents occur during?
* Return a table showing how many accidents occurred in each hour of the day in 2015, sorted by the the number of accidents which occurred each hour. Use either the accident_2015 or accident_2016 table for this, and the timestamp_of_crash column (there is an hour_of_crash column, but if you use that one you won't get a chance to practice with dates).

**Hint:** You will probably want to use the [EXTRACT() function](https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#extract_1) for this.

In [3]:
accidents.head('accident_2015')

,state_number,state_name,consecutive_number,number_of_vehicle_forms_submitted_all,number_of_motor_vehicles_in_transport_mvit,number_of_parked_working_vehicles,number_of_forms_submitted_for_persons_not_in_motor_vehicles,number_of_persons_not_in_motor_vehicles_in_transport_mvit,number_of_persons_in_motor_vehicles_in_transport_mvit,number_of_forms_submitted_for_persons_in_motor_vehicles,...,minute_of_ems_arrival_at_hospital,related_factors_crash_level_1,related_factors_crash_level_1_name,related_factors_crash_level_2,related_factors_crash_level_2_name,related_factors_crash_level_3,related_factors_crash_level_3_name,number_of_fatalities,number_of_drunk_drivers,timestamp_of_crash
0,34,New Jersey,340090,2,1,1,0,0,1,1,...,26,0,None,0,None,0,None,1,1,2015-04-05 21:05:00+00:00
1,35,New Mexico,350112,1,1,0,0,0,2,2,...,99,0,None,0,None,0,None,1,1,2015-05-10 00:03:00+00:00
2,49,Utah,490197,1,1,0,0,0,3,3,...,99,0,None,0,None,0,None,1,0,2015-08-04 15:50:00+00:00
3,10,Delaware,100063,1,1,0,0,0,1,1,...,3,0,None,0,None,0,None,1,1,2015-06-13 18:41:00+00:00
4,24,Maryland,240440,1,1,0,0,0,1,1,...,24,0,None,0,None,0,None,1,1,2015-12-27 19:36:00+00:00

In [4]:
# Solution Version 1
query = """SELECT count(*), hour_of_crash
            FROM `bigquery-public-data.nhtsa_traffic_fatalities.accident_2015`
            GROUP BY hour_of_crash
            ORDER BY count(*) DESC
        """
df = accidents.query_to_pandas_safe(query, max_gb_scanned=0.01)
df

     f0_  hour_of_crash
0   1895             18
1   1862             20
2   1838             17
3   1811             21
4   1784             19
5   1686             15
6   1650             16
7   1554             22
8   1511             14
9   1387             13
10  1334             23
11  1265              0
12  1226              1
13  1223             12
14  1207              2
15  1202              6
16  1146              7
17  1126             11
18  1019             10
19  1000              5
20   958              9
21   946              3
22   910              8
23   751              4
24   248             99

In [5]:
# Solution Version 2
query = """SELECT COUNT(*), EXTRACT( HOUR FROM timestamp_of_crash )
            FROM `bigquery-public-data.nhtsa_traffic_fatalities.accident_2015`
            GROUP BY EXTRACT( HOUR FROM timestamp_of_crash )
            ORDER BY COUNT(*) DESC
        """
df = accidents.query_to_pandas_safe(query, max_gb_scanned=0.01)
df

     f0_  f1_
0   1895   18
1   1862   20
2   1838   17
3   1811   21
4   1784   19
5   1686   15
6   1650   16
7   1554   22
8   1513    0
9   1511   14
10  1387   13
11  1334   23
12  1226    1
13  1223   12
14  1207    2
15  1202    6
16  1146    7
17  1126   11
18  1019   10
19  1000    5
20   958    9
21   946    3
22   910    8
23   751    4

#### 2) Which state has the most hit and runs?
* Return a table with the number of vehicles registered in each state that were involved in hit-and-run accidents, sorted by the number of hit and runs. Use either the vehicle_2015 or vehicle_2016 table for this, especially the registration_state_name and hit_and_run columns (it may be helpful to view the hit_and_run column to understand its contents).

In [6]:
accidents.head('vehicle_2015')

,state_number,consecutive_number,vehicle_number,number_of_motor_vehicles_in_transport_mvit,number_of_occupants,day_of_crash,month_of_crash,hour_of_crash,minute_of_crash,first_harmful_event,...,critical_event_precrash_name,attempted_avoidance_maneuver,attempted_avoidance_maneuver_name,pre_impact_stability,pre_impact_location,crash_type,crash_type_name,fatalities_in_vehicle,driver_drinking,timestamp_of_crash
0,4,40725,1,1,2,26,10,14,15,5,...,Turning Left at Junction,1,No Avoidance Maneuver,Tracking,1,0,No Impact,1,Drinking,2015-10-26 14:15:00+00:00
1,23,230037,1,1,1,29,5,23,15,11,...,Animal in Road,99,Unknown,Tracking,1,13,"SINGLE DRIVER, CONFIGURATION C: FORWARD IMPACT...",1,No Drinking,2015-05-29 23:15:00+00:00
2,29,290526,1,1,1,5,9,20,10,5,...,Traveling Too Fast For Conditions,1,No Avoidance Maneuver,Tracking,4,0,No Impact,1,No Drinking,2015-09-05 20:10:00+00:00
3,53,530079,1,1,1,5,3,18,15,39,...,Unknown Cause of Control Loss,99,Unknown,Skidding Longitudinally – Rotation Less Than 3...,4,1,"SINGLE DRIVER, CONFIGURATION A: RIGHT ROADSIDE...",1,No Drinking,2015-03-05 18:15:00+00:00
4,36,360486,1,1,1,30,7,20,49,5,...,Unknown Cause of Control Loss,99,Unknown,Tracking,5,0,No Impact,1,Drinking,2015-07-30 20:49:00+00:00

In [7]:
# Use the Scheme to help find the relavant columns (registration_state_name and hit_and_run)
accidents.table_schema('vehicle_2015')

[SchemaField('state_number', 'INTEGER', 'NULLABLE', 'This data element identifies the state in which the crash occurred. The codes are from the General Services Administration’s (GSA) publication of worldwide Geographic Location Codes (GLC). For more info on the codes, please look at <C1/V1/D1/PC1/P1/NM1 State Number> section in the pdf: https://crashstats.nhtsa.dot.gov/Api/Public/ViewPublication/812315', ()),
 SchemaField('consecutive_number', 'INTEGER', 'NULLABLE', 'This data element is the unique case number assigned to each crash. It appears on each data file and is used to merge information from the data files together. xxxxxx Two Characters for State Code followed by Four Characters for Case Number', ()),
 SchemaField('vehicle_number', 'INTEGER', 'NULLABLE', 'This data element is the consecutive number assigned to each vehicle in the case. This data element appears on each vehicle level data file and is used in conjunction with the ST_CASE data element to merge information from vehicle level data files. 000-999 Assigned Number of Motor Vehicle', ()),
 SchemaField('number_of_motor_vehicles_in_transport_mvit', 'INTEGER', 'NULLABLE', 'This data element is a count of the number of vehicles in-transport involved in the crash. Legally parked vehicles are not included. 001-999 Number of Vehicle Forms', ()),
 SchemaField('number_of_occupants', 'INTEGER', 'NULLABLE', 'This data element is a count of the number of occupants in this vehicle. 00 None 01-95 Actual Number of Occupants in The Vehicle 96 96 or More Occupants in The Vehicle -- Unknown – Only Injured Reported 98 Not Reported (2010 Only) 99 Unknown', ()),
 SchemaField('day_of_crash', 'INTEGER', 'NULLABLE', 'This data element records the day of the month on which the crash occurred. 01-31 Day of the Month of the Crash -- Unknown', ()),
 SchemaField('month_of_crash', 'INTEGER', 'NULLABLE', 'This data element records the month in which the crash occurred.For more info on the codes, please look at C8A Month of Crash section in the pdf: https://crashstats.nhtsa.dot.gov/Api/Public/ViewPublication/812315', ()),
 SchemaField('hour_of_crash', 'INTEGER', 'NULLABLE', 'This data element records the hour at which the crash occurred.0-23 Hour -- Not Applicable or Not Notified 99 Unknown', ()),
 SchemaField('minute_of_crash', 'INTEGER', 'NULLABLE', 'This data element records the minutes after the hour at which the crash occurred. 00-59 Minute -- Not Applicable or Not Notified 99 Unknown', ()),
 SchemaField('first_harmful_event', 'INTEGER', 'NULLABLE', 'This data element describes the first injury or damage producing event of the crash. For more info on the codes, please look at C19 First Harmful Event section in the pdf: https://crashstats.nhtsa.dot.gov/Api/Public/ViewPublication/812315', ()),
 SchemaField('first_harmful_event_name', 'STRING', 'NULLABLE', 'This data element describes the first injury or damage producing event of the crash.', ()),
 SchemaField('manner_of_collision', 'INTEGER', 'NULLABLE', 'This data element describes the orientation of two motor vehicles in-transport when they are involved in the “First Harmful Event” of a collision crash. If the “First Harmful Event” is not a collision between two motor vehicles in-transport it is classified as such. For more info on the codes, please look at C20 Manner of Collision section in the pdf: https://crashstats.nhtsa.dot.gov/Api/Public/ViewPublication/812315', ()),
 SchemaField('unit_type', 'STRING', 'NULLABLE', 'This data element identifies the type of unit that applies to this motor vehicle at the time it became an involved vehicle in the crash and was reported as a unit on the PAR. -- Motor Vehicle in Transport 1 Motor Vehicle in Transport (Inside or Outside the Trafficway)', ()),
 SchemaField('hit_and_run', 'STRING', 'NULLABLE', 'This data element identifies whether this vehicle was a contact vehicle in the crash that did not stop to render aid (this can include drivers who flee the scene on foot). Hit and run is coded when a motor vehicle in-transport, or its driver, departs from the scene; vehicles not intransport are excluded. It does not matter whether the hit-and-run vehicle was striking or struck. 0 No 1 Yes -- Not Reported 9 Unknown', ()),
 SchemaField('registration_state', 'INTEGER', 'NULLABLE', 'This element identifies the state in which this vehicle was registered. For more info on the codes, please look at V7 Registration State section in the pdf: https://crashstats.nhtsa.dot.gov/Api/Public/ViewPublication/812315', ()),
 SchemaField('registration_state_name', 'STRING', 'NULLABLE', 'This element identifies the state in which this vehicle was registered.', ()),
 SchemaField('registered_vehicle_owner', 'INTEGER', 'NULLABLE', 'This data element identifies the type of registered owner of the vehicle. 0 Not Applicable, Vehicle Not Registered 1 Driver (of This Vehicle) Was Registered Owner 2 Driver (of This Vehicle) Not Registered Owner (Other Private Owner) 3 Vehicle Registered as Business/Company/Government Vehicle 4 Vehicle Registered as Rental Vehicle 5 Vehicle Was Stolen (Reported By Police) -- Driverless Vehicle 6 Driverless/Motor Vehicle Parked/Stopped Off Roadway 9 Unknown', ()),
 SchemaField('registered_vehicle_owner_name', 'STRING', 'NULLABLE', 'This data element identifies the type of registered owner of the vehicle.', ()),
 SchemaField('vehicle_make', 'INTEGER', 'NULLABLE', 'This data element identifies the make (manufacturer) of this vehicle. For more info on the codes, please look at V9 Vehicle Make section in the pdf: https://crashstats.nhtsa.dot.gov/Api/Public/ViewPublication/812315', ()),
 SchemaField('vehicle_make_name', 'STRING', 'NULLABLE', 'This data element identifies the make (manufacturer) of this vehicle', ()),
 SchemaField('vehicle_model', 'INTEGER', 'NULLABLE', 'This data element identifies the model of this vehicle within a given make. For more info on the codes, please look at V10 Vehicle Model section in the pdf: https://crashstats.nhtsa.dot.gov/Api/Public/ViewPublication/812315', ()),
 SchemaField('make_model_combined', 'INTEGER', 'NULLABLE', 'This derived data element represents the 5-digit combination of two data elements, the 2-digit “Vehicle Make” code (MAKE) followed by the 3-digit “Vehicle Model” code (MODEL). For more info on the codes, please look at V100 Make Model Combined section in the pdf: https://crashstats.nhtsa.dot.gov/Api/Public/ViewPublication/812315', ()),
 SchemaField('body_type', 'INTEGER', 'NULLABLE', 'This data element identifies a classification of this vehicle based on its general body configuration, size, shape, doors, etc. For more info on the codes, please look at V11 Body Type section in the pdf: https://crashstats.nhtsa.dot.gov/Api/Public/ViewPublication/812315', ()),
 SchemaField('body_type_name', 'STRING', 'NULLABLE', 'This data element identifies a classification of this vehicle based on its general body configuration, size, shape, doors, etc.', ()),
 SchemaField('vehicle_model_year', 'INTEGER', 'NULLABLE', "This data element identifies the manufacturer's model year of this vehicle. 0000-9997 Actual year of vehicle manufacture 9998 Not Reported 9999 Unknown", ()),
 SchemaField('vehicle_identification_number_vin', 'STRING', 'NULLABLE', 'This data element records the vehicle identification number (VIN) of this vehicle assigned by the vehicle manufacturer. The VIN contains information on the vehicle such as: manufacturer, model year, model, body type, restraint type, etc. -- First 10 Characters xxxxxxxxxxxx  First 12 Characters 000000000000 No VIN Required 888888888888 Not Reported 999999999999 Unknown', ()),
 SchemaField('vin_character_1', 'STRING', 'NULLABLE', 'This data element represents the first character in the VIN string for this vehicle. x First Character in the VIN String', ()),
 SchemaField('vin_character_2', 'STRING', 'NULLABLE', 'This data element represents the second character in the VIN string for this vehicle. x Second Character in the VIN String', ()),
 SchemaField('vin_character_3', 'STRING', 'NULLABLE', 'This data element represents the third character in the VIN string for this vehicle. x Third Character in the VIN String', ()),
 SchemaField('vin_character_4', 'STRING', 'NULLABLE', 'This data element represents the fourth character in the VIN string for this vehicle. x Fourth Character in the VIN String', ()),
 SchemaField('vin_character_5', 'STRING', 'NULLABLE', 'This data element represents the fifth character in the VIN string for this vehicle. x Fifth Character in the VIN String', ()),
 SchemaField('vin_character_6', 'STRING', 'NULLABLE', 'This data element represents the sixth character in the VIN string for this vehicle. x Sixth Character in the VIN String', ()),
 SchemaField('vin_character_7', 'STRING', 'NULLABLE', 'This data element represents the seventh character in the VIN string for this vehicle. x Seventh Character in the VIN String', ()),
 SchemaField('vin_character_8', 'STRING', 'NULLABLE', 'This data element represents the eighth character in the VIN string for this vehicle. x Eighth Character in the VIN String', ()),
 SchemaField('vin_character_9', 'STRING', 'NULLABLE', 'This data element represents the ninth character in the VIN string for this vehicle. x Ninth Character in the VIN String', ()),
 SchemaField('vin_character_10', 'STRING', 'NULLABLE', 'This data element represents the tenth character in the VIN string for this vehicle. x Tenth Character in the VIN String', ()),
 SchemaField('vin_character_11', 'STRING', 'NULLABLE', 'This data element represents the eleventh character in the VIN string for this vehicle. x Eleventh Character in the VIN String', ()),
 SchemaField('vin_character_12', 'STRING', 'NULLABLE', 'This data element represents the twelfth character in the VIN string for this vehicle. x Twelfth Character in the VIN String', ()),
 SchemaField('vehicle_trailing', 'STRING', 'NULLABLE', 'This data element identifies whether this vehicle had any attached trailing units or was towing another motor vehicle. A trailing unit can be a horse trailer, fifth wheel trailer, camper, boat, truck trailer, towed vehicle or any other trailer. 0 No Trailing Unit 1 Yes, One Trailing Unit 2 Yes, Two Trailing Units 3 Yes, Three or More Trailing Units 4 Yes, Number of Trailing Units Unknown -- Vehicle Towing another Motor Vehicle 5 Vehicle Towing another Motor Vehicle – Fixed Linkage 6 Vehicle Towing another Motor Vehicle – Non-Fixed Linkage 9 Unknown', ()),
 SchemaField('jackknife', 'STRING', 'NULLABLE', 'This data element identifies whether this vehicle experienced a jackknife anytime during the unstabilized situation. 0 Not an Articulated Vehicle 1 No -- Yes 2 Yes, First Event 3 Yes, Subsequent Event', ()),
 SchemaField('mcid_issuing_authority', 'INTEGER', 'NULLABLE', 'This data element records the issuing authority if applicable to this vehicle. 00 Not Applicable 01-56 FARS State Code 57 US DOT 58 MC/MX (ICC) 77 Not Reported 88 None 95 Canada 96 Mexico 99 Unknown', ()),
 SchemaField('mcid_identification_number', 'STRING', 'NULLABLE', 'This data element records the motor carrier identification number if applicable to this vehicle. xxxxxxxxx Actual 9-Digit Number 000000000 Not Applicable 777777777 Not Reported 888888888 None 999999999 Unknown', ()),
 SchemaField('motor_carrier_identification_number_mcid', 'STRING', 'NULLABLE', 'This data element records the issuing authority and motor carrier identification number if applicable to this vehicle. This data element is the combination of two data elements, MCARR_I1 and MCARR_I2. xxxxxxxxxxx 11-Character Combination of MCARR_I1 followed by MCARR_I2 00000000000 Not Applicable 77777777777 Not Reported 88888888888 None 99999999999 Unknown', ()),
 SchemaField('gross_vehicle_weight_rating', 'STRING', 'NULLABLE', 'This data element identifies the gross vehicle weight rating of this vehicle if applicable. 0 Not Applicable 1 10,000 lbs or Less 2 10,001 lbs - 26,000 lbs 3 26,001 lbs or More 8 Not Reported 9 Unknown', ()),
 SchemaField('vehicle_configuration', 'INTEGER', 'NULLABLE', 'This data element identifies the general configuration of this vehicle if applicable. For more info on the codes, please look at V18 Vehicle Configuration section in the pdf: https://crashstats.nhtsa.dot.gov/Api/Public/ViewPublication/812315', ()),
 SchemaField('vehicle_configuration_name', 'STRING', 'NULLABLE', 'This data element describes the general configuration of this vehicle if applicable', ()),
 SchemaField('cargo_body_type', 'INTEGER', 'NULLABLE', 'This data element identifies the primary cargo carrying capability of this vehicle if applicable. For more info on the codes, please look at V19 Cargo Body Type section in the pdf: https://crashstats.nhtsa.dot.gov/Api/Public/ViewPublication/812315', ()),
 SchemaField('cargo_body_type_name', 'STRING', 'NULLABLE', 'This data element describes the primary cargo carrying capability of this vehicle if applicable.', ()),
 SchemaField('hazardous_material_involvement', 'STRING', 'NULLABLE', 'This data element identifies whether this vehicle was carrying hazardous materials. 1 No 2 Yes', ()),
 SchemaField('hazardous_material_placard', 'INTEGER', 'NULLABLE', 'This data element identifies the presence of hazardous materials for this vehicle and whether this vehicle displayed a hazardous materials placard. 0 Not Applicable 1 No 2 Yes 8 Not Reported', ()),
 SchemaField('hazardous_material_identification_number', 'INTEGER', 'NULLABLE', 'This data element identifies the 4-digit hazardous material identification number for this vehicle. 0000 Not Applicable xxxx Actual 4-Digit Number 8888 Not Reported', ()),
 SchemaField('hazardous_material_class_number', 'INTEGER', 'NULLABLE', 'This data element identifies the single-digit hazardous material class number for this vehicle. 0 Not Applicable 1-9 Actual Number 88 Not Reported', ()),
 SchemaField('release_of_hazardous_material_from_the_cargo_compartment', 'STRING', 'NULLABLE', 'This data element identifies whether any hazardous cargo was released from the cargo tank or compartment of this vehicle. 0 Not Applicable 1 No 2 Yes 8 Not Reported', ()),
 SchemaField('bus_use', 'STRING', 'NULLABLE', 'This data element describes the common type of bus service this vehicle was being used as at the time of the crash or the primary use for the bus if not in service at the time of the crash. 00 Not a Bus 01 School Bus 04 Intercity Bus 05 Charter/Tour Bus 06 Transit/Commuter Bus 07 Shuttle Bus 08 Modified for Personal/Private Use 98 Not Reported 99 Unknown', ()),
 SchemaField('special_use', 'INTEGER', 'NULLABLE', 'This data element identifies any special use associated with this vehicle at the time of the crash. For more info on the codes, please look at V22 Special Use section in the pdf: https://crashstats.nhtsa.dot.gov/Api/Public/ViewPublication/812315', ()),
 SchemaField('special_use_name', 'STRING', 'NULLABLE', 'This data element identifies any special use associated with this vehicle at the time of the crash.', ()),
 SchemaField('emergency_motor_vehicle_use', 'STRING', 'NULLABLE', 'This data element identifies whether this vehicle was engaged in emergency use. Emergency Use indicates operation of any motor vehicle that is legally authorized by a government authority to respond to emergencies with or without the use of emergency warning equipment, such as a police vehicle, fire truck or ambulance while actually engaged in such response. -- No 0 Not Applicable -- Yes 2 Non-Emergency, Non-Transport 3 Non-Emergency Transport 4 Emergency Operation, Emergency Warning Equipment Not In Use 5 Emergency Operation, Emergency Warning Equipment In Use 6 Emergency Operation, Emergency Warning Equipment In Use Unknown 8 Not Reported 9 Unknown', ()),
 SchemaField('travel_speed', 'INTEGER', 'NULLABLE', 'This data element records the speed the vehicle was traveling prior to the occurrence of the crash as reported by the investigating officer. 000 Stopped Motor Vehicle in Transport 001-151 Reported Speed Up to 151 mph -- Speed Greater than 96 mph 997 Speed Greater than 151 mph 998 Not Reported 999 Unknown', ()),
 SchemaField('underride_override', 'INTEGER', 'NULLABLE', 'This data element identifies this vehicle’s involvement in an underride or override during the crash. For more info on the codes, please look at V25 Underride/Override section in the pdf: https://crashstats.nhtsa.dot.gov/Api/Public/ViewPublication/812315', ()),
 SchemaField('rollover', 'STRING', 'NULLABLE', 'This data element identifies this vehicle’s involvement in a rollover or overturn during the crash. Rollover is defined as any vehicle rotation of 90 degrees or more about any true longitudinal or lateral axis. Rollover can occur at any time during the crash. 0 No Rollover -- First Event 1 Rollover, Tripped by Object/Vehicle -- Subsequent Event 2 Rollover, Untripped 9 Rollover, Unknown Type', ()),
 SchemaField('location_of_rollover', 'STRING', 'NULLABLE', "This data element identifies the location of the trip point or start of this vehicle's roll. 0 No Rollover 1 On Roadway 2 On Shoulder 3 On Median/Separator 4 In Gore 5 On Roadside 6 Outside of Trafficway 7 In Parking Lane/Zone 9 Unknown", ()),
 SchemaField('initial_contact_point', 'INTEGER', 'NULLABLE', 'This data element identifies the area on this vehicle that produced the first instance of injury to non-motorists or occupants of this vehicle, or that resulted in the first instance of damage to other property or to this vehicle. For more info on the codes, please look at V28A Initial Contact Point section in the pdf: https://crashstats.nhtsa.dot.gov/Api/Public/ViewPublication/812315', ()),
 SchemaField('extent_of_damage', 'STRING', 'NULLABLE', 'This data element records the amount of damage sustained by this vehicle as indicated in the case materials based on an operational damage scale. 0 No Damage 2 Minor Damage 4 Functional Damage 6 Disabling Damage 8 Not Reported 9 Unknown', ()),
 SchemaField('vehicle_removal', 'STRING', 'NULLABLE', 'This data element describes the mode by which this vehicle left the scene of the crash. -- Driven Away -- Towed Away 2 Towed Due to Disabling Damage -- Abandoned/Left Scene 3 Towed Not Due to Disabling Damage -- Not Towed Away -- Abandoned/Left at Scene 5 Not Towed 8 Not Reported 9 Unknown', ()),
 SchemaField('most_harmful_event', 'INTEGER', 'NULLABLE', 'This data element describes the event that resulted in the most severe injury or, if no injury, the greatest property damage involving this vehicle. For more info on the codes, please look at V32 Most Harmful Event section in the pdf: https://crashstats.nhtsa.dot.gov/Api/Public/ViewPublication/812315', ()),
 SchemaField('related_factors_vehicle_level_1', 'INTEGER', 'NULLABLE', 'This data element records factors related to this vehicle expressed by the investigating officer. For more info on the codes, please look at V33 Related Factors- Vehicle Level section in the pdf: https://crashstats.nhtsa.dot.gov/Api/Public/ViewPublication/812315', ()),
 SchemaField('related_factors_vehicle_level_2', 'INTEGER', 'NULLABLE', 'This data element records factors related to this vehicle expressed by the investigating officer. For more info on the codes, please look at V33 Related Factors- Vehicle Level section in the pdf: https://crashstats.nhtsa.dot.gov/Api/Public/ViewPublication/812315', ()),
 SchemaField('fire_occurrence', 'STRING', 'NULLABLE', 'This data element identifies whether a fire in any way related to the crash occurred in this vehicle. -- No Fire 0 No or Not Reported -- Fire Occurred in This Vehicle during Crash 1 Yes -- Fire Occurred in This Vehicle and Initiated Fire/Explosion in Another Vehicle', ()),

In [8]:
# Take a look at the possible values that hit_and_run may take 
query = """SELECT DISTINCT( hit_and_run )
            FROM `bigquery-public-data.nhtsa_traffic_fatalities.vehicle_2015`
        """
df = accidents.query_to_pandas_safe(query, max_gb_scanned=0.01)
df

  hit_and_run
0          No
1         Yes
2     Unknown

In [9]:
query = """SELECT COUNT(*), registration_state_name
            FROM `bigquery-public-data.nhtsa_traffic_fatalities.vehicle_2015`
            WHERE hit_and_run = "Yes"
            GROUP BY registration_state_name
            ORDER BY COUNT(*) DESC
        """
df = accidents.query_to_pandas_safe(query, max_gb_scanned=0.01)
df

    f0_                            registration_state_name
0   834                                            Unknown
1   155                                         California
2    96                                            Florida
3    86                                              Texas
4    38                                           New York
5    33                                           Michigan
6    31                                            Arizona
7    30                                     North Carolina
8    29                                          Wisconsin
9    26                                       Pennsylvania
10   26                                            Georgia
11   24                                           Illinois
12   24                                         New Jersey
13   22                                          Louisiana
14   21                                          Tennessee
15   20                                            Indiana
16   19                                           Maryland
17   19                                            Alabama
18   19                                           Colorado
19   18                                               Ohio
20   17                                               Iowa
21   16                                      Massachusetts
22   16                                     South Carolina
23   15                                           Virginia
24   15                                             Nevada
25   15                                    No Registration
26   14                                           Oklahoma
27   13                                           Kentucky
28   12                                         New Mexico
29   10                                        Mississippi
30   10                                         Washington
31   10                                        Connecticut
32    8                                           Arkansas
33    8                                             Kansas
34    7                                             Oregon
35    6                                           Nebraska
36    6                                          Minnesota
37    5                                               Utah
38    5                                              Maine
39    5                                           Delaware
40    4                       Multiple State Registrations
41    3                                      West Virginia
42    3                                           Missouri
43    3  Other Registration (Includes Native American I...
44    3                                              Idaho
45    2                                             Alaska
46    2                                            Montana
47    1                                            Vermont
48    1                              Other Foreign Country
49    1                                     Not Applicable
50    1                                             Hawaii
51    1                                      New Hampshire
52    1                               District of Columbia

---
# Keep Going
[Click here](https://www.kaggle.com/dansbecker/as-with) to learn how *WITH-AS* clauses  can clean up your code and help you construct more complex queries.

# Feedback
Bring any questions or feedback to the [Learn Discussion Forum](kaggle.com/learn-forum).

----

*This tutorial is part of the [SQL Series](https://www.kaggle.com/learn/sql) on Kaggle Learn.*